config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'women#index'

  resources :coordinates
  resources :men
  resources :women
  resources :owners
  resources :favorites do
    post :remove, on: :collection
  end
  resources :men_coordinates
  resources :women_coordinates
  get '/sitemap' => redirect('https://s3-ap-northeast-1.amazonaws.com/styly/sitemaps/sitemap.xml.gz')
end

app/models/coordinate.rb
class Coordinate < ActiveRecord::Base
  has_many :photos, as: :imageable, dependent: :destroy
  belongs_to :owner

  validates :dress_season, presence: true

  accepts_nested_attributes_for :photos

  acts_as_votable

  def self.search(owner_id)
    where(owner_id: owner_id.to_i)
  end

  def previous(owner, id)
    owner.coordinates.where('id < ?', id).order('id DESC').first
  end

  def next(owner, id)
    owner.coordinates.where('id > ?', id).order('id ASC').first
  end
end

app/models/owner.rb
class Owner < ActiveRecord::Base
  has_many :coordinates, dependent: :destroy

  scope :recent, -> { order(updated_at: :desc) }
  scope :man, -> { where(man_flag: true) }
  scope :woman, -> { where(woman_flag: true) }
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :imageable, polymorphic: true

  delegate :url, to: :image

  # TODO: use dynamic configuration
  # see https://github.com/thoughtbot/paperclip#dynamic-configuration
  has_attached_file :image, styles: { medium: '350x200>' }
  validates_attachment_presence :image
  validates_attachment_content_type :image, content_type: %r{\Aimage\/.*\Z}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/coordinates_controller.rb
class CoordinatesController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @coordinates = Coordinate.search(params[:owner_id])
  end

  def show
    @coordinate = Coordinate.find(params[:id])
  end

  def new
    @coordinate = Coordinate.new
    @coordinate.photos.build
  end

  def create
    @coordinate = Coordinate.new(coordinate_params)
    if @coordinate.save
      if Owner.where("name like '%" + params[:coordinate][:owner][:name] + "%'").present?
        owner = Owner.where("name like '%" + params[:coordinate][:owner][:name] + "%'").first
        @coordinate.update(owner_id: owner.id)
      else
        if params[:coordinate][:owner][:man_flag].present?
          new_owner = Owner.create(name: params[:coordinate][:owner][:name], occupation: params[:coordinate][:owner][:occupation], man_flag: true)
        else
          new_owner = Owner.create(name: params[:coordinate][:owner][:name], occupation: params[:coordinate][:owner][:occupation], woman_flag: true)
        end
        @coordinate.update(owner_id: new_owner.id)
      end
      if @coordinate.owner.man_flag == true
        redirect_to men_coordinate_path(id: @coordinate.id)
      else
        redirect_to women_coordinate_path(id: @coordinate.id)
      end
    else
      render :new
    end
  end

  def destroy
    @coordinate = Coordinate.find(params[:id])
    @coordinate.delete
    redirect_to @coordinate
  end

  private

  def coordinate_params
    params.require(:coordinate).permit(:dress_season, photos_attributes: :image)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @coordinates = current_user.votes.up.for_type(Coordinate).order('created_at desc').votables
  end

  def create
    @coordinate = Coordinate.find(params[:coordinate_id])
    @coordinate.liked_by current_user
  end

  def remove
    @coordinate = Coordinate.find(params[:coordinate_id])
    @coordinate.disliked_by current_user
  end
end

app/controllers/men_controller.rb
class MenController < ApplicationController
  def index
    @owners = Owner.man.shuffle
  end

  def show
    @owner = Owner.find(params[:id])
    @coordinates = @owner.coordinates.includes(:photos).order(:id)
  end
end

app/controllers/men_coordinates_controller.rb
class MenCoordinatesController < ApplicationController
  def index
    @coordinates = Coordinate.search(params[:owner_id])
  end

  def show
    @coordinate = Coordinate.find(params[:id])
  end
end

app/controllers/mens_controller.rb
class MensController < ApplicationController
  def index
    @owners = Owner.man.shuffle
  end

  def show
    @owner = Owner.find(params[:id])
    @coordinates = @owner.coordinates.includes(:photos).shuffle
  end
end

app/controllers/mens_coordinates_controller.rb
class MensCoordinatesController < ApplicationController
  def index
    @coordinates = Coordinate.search(params[:owner_id])
  end
  
  def show
    @coordinate = Coordinate.find(params[:id])
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController
  def index
    @owners = Owner.all.shuffle
  end

  def show
    @owner = Owner.find(params[:id])
    @coordinates = @owner.coordinates.includes(:photos).shuffle
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    callback_from :facebook
  end

  def twitter
    callback_from :twitter
  end

  private

  def callback_from(provider)
    provider = provider.to_s

    @user = User.find_for_oauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t('devise.omniauth_callbacks.success', kind: provider.capitalize)
      sign_in_and_redirect @user, event: :authentication
    else
      session["devise.#{provider}_data"] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/controllers/women_controller.rb
class WomenController < ApplicationController
  def index
    @owners = Owner.includes(:coordinates).woman.shuffle
  end

  def show
    @owner = Owner.find(params[:id])
    @coordinates = @owner.coordinates.includes(:photos).order(:id)
  end
end

app/controllers/women_coordinates_controller.rb
class WomenCoordinatesController < ApplicationController
  def index
    @coordinates = Coordinate.search(params[:owner_id])
  end
  
  def show
    @coordinate = Coordinate.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coordinates/_add_to_favorites.html.erb
<div class='favorite_button text-center'>
  <div class='btn btn-default'>
    <%= link_to 'Favorite', favorites_path(coordinate_id: @coordinate.id), method: :post, remote: true %>
  </div>
</div>

<div id='favorite_result'>
</div>

app/views/coordinates/_remove_from_favorites.html.erb
<div class='unfavorite_button text-center'>
  <div class='btn btn-default'>
    <%= link_to 'Unfavorite', remove_favorites_path(coordinate_id: @coordinate.id), method: :post, remote: true %>
  </div>
</div>

<div id='unfavorite_result'>
</div>

app/views/coordinates/_search.html.erb
<%= form_tag coordinates_path, method: :get do %>
  <%= select_tag :owner_id, options_from_collection_for_select(Owner.all, :id, :name, params[:owner_id]), { include_blank: 'people' } %>
  <%= button_tag type: 'submit', class: 'btn btn-default' do %>
    <i class='fa fa-search'></i>
  <% end %>
<% end %>

app/views/coordinates/index.html.erb
<header class='search_form text-center'>
  <%= render 'coordinates/search' %>
</header>

<div class='coordinates_list'>
  <% @coordinates.each do |coordinate| %>
    <%= link_to coordinate do %>
      <div class='list'>
        <div class='list_body'>
          <% coordinate.photos.each do |photo| %>
            <%= image_tag photo.image.url, class: 'coordinate_image' %>
          <% end %>
          <div class='name'>
            <%= coordinate.owner.name %>
          </div>
          <div class='season'>
            dress_season: <%= coordinate.dress_season %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/coordinates/new.html.erb
<%= form_for @coordinate do |f| %>
  <% if @coordinate.errors.any? %>
    <div id='error_explanation'>
      <ul>
      <% @coordinate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.fields_for :photos do |ph| %>
    <div class='form-group post_image'>
      <i class='fa fa-camera'></i><%= ph.label :image, t('.select_photo') %>
      <%= ph.file_field :image %>
    </div>
  <% end %>

  <%= f.fields_for :owner do |person| %>
    <div class='form-group'>
      <%= person.label :name, 'person_name' %>
      <%= person.text_field :name, class: 'form-control' %>
    </div>

    <div class='form-group'>
      <%= person.label :occupation, 'occupation' %>
      <%= person.text_field :occupation, class: 'form-control' %>
    </div>

    <div class='form-group'>
      Man<%= person.radio_button :man_flag, true %>
      Woman<%= person.radio_button :woman_flag, true %>
    </div>
  <% end %>

  <div class='form-group'>
    <%= f.label :dress_season, 'dress_season' %>
    <%= f.text_field :dress_season, class: 'form-control' %>
  </div>

  <div class='form-group actions submit text-center'>
    <%= f.submit 'Post', class: 'btn btn-default' %>
  </div>
<% end %>

app/views/coordinates/show.html.erb
<div class='coordinate'>
  <div class='person_name text-center'>
    <%= @coordinate.owner.name %>
  </div>
  <div class='image'>
    <% @coordinate.photos.each do |photo| %>
      <%= image_tag photo.image.url, class: 'img-responsive' %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.voted_up_on? @coordinate %>
      <%= render 'remove_from_favorites' %>
    <% else %>
      <%= render 'add_to_favorites' %>
    <% end %>
  <% else %>
    <div class='not_login'>
      <%= render 'add_to_favorites' %>
    </div>
  <% end %>
  <hr>
  <div class='dress_season text-center'>
    dress_season: <%= @coordinate.dress_season %>
  </div>
  <hr>
  <div class='occupation text-center'>
    occupation: <%= @coordinate.owner.occupation %>
  </div>
  <hr>

  <% if current_user %>
    <% if current_user.email == 'takuyashiratake0622@icloud.com' %>
      <div class='text-center'>
        <%= link_to 'Delete', coordinate_path, method: :delete, class: 'btn btn-default' %>
      </div>
    <% end %>
  <% end %>

  <div class='show_more text-center'>
    <%= link_to 'Show more', owner_path(id: @coordinate.owner), class: 'btn btn-default' %>
  </div>
</div>

<script>
  jQuery(function() {
    $('.not_login').click(function() {
      location.href = '/users/sign_in';
    })
  });
</script>

app/views/favorites/create.js.erb
$('.favorite_button').hide();
$('#favorite_result').html(
  "<%= j(render 'coordinates/remove_from_favorites') %>"
);

app/views/favorites/remove.js.erb
$('.unfavorite_button').hide();
$('#unfavorite_result').html(
  "<%= j(render 'coordinates/add_to_favorites') %>"
);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Styly</title>
  <meta name='viewport' content='width=device-width, initial-scale=1 user-scalable=no'>
  <%= render 'layouts/meta_tags' %>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'layouts/google_tag_manager' %>
  <header>
    <nav class='navbar navbar-custom'>
      <div>
        <% if params[:controller] == 'women' || params[:controller] == 'women_coordinates' %>
          <h3 class='logo text-center text-muted'><%= link_to 'Styly', root_path %></h3>
        <% else %>
          <h3 class='logo text-center text-muted'><%= link_to 'Styly', men_path %></h3>
        <% end %>
      </div>

      <% if params[:controller] == 'women' || params[:controller] == 'women_coordinates' %>
        <div class='man_button text-center'>
          <%= link_to 'Man', men_path, class: 'btn btn-default' %>
        </div>
      <% elsif params[:controller] == 'men' || params[:controller] == 'men_coordinates' %>
        <div class='woman_button text-center'>
          <%= link_to 'Woman', root_path, class: 'btn btn-default' %>
        </div>
      <% end %>

      <% if user_signed_in? %>
        <% if params[:controller] == 'women' || params[:controller] == 'women_coordinates' %>
          <div class='woman user_favorites text-center'>
            <%= link_to 'Favorites', favorites_path, class: 'btn btn-default' %>
          </div>
        <% elsif params[:controller] == 'men' || params[:controller] == 'men_coordinates' %>
          <div class='man user_favorites text-center'>
            <%= link_to 'Favorites', favorites_path, class: 'btn btn-default' %>
          </div>
        <% end %>
      <% else %>
        <div class='sign_in_link text-center'>
          <%= link_to 'Sign in', new_user_session_path, class: 'btn btn-default' %>
        </div>
      <% end %>
    </nav>
  </header>

  <p class='notice text-center'><%= notice %></p>
  <p class='alert text-center'><%= alert %></p>

<%= yield %>

</body>
</html>

app/views/men/index.html.erb
<div class='search_form text-center'>
  <%= form_tag men_coordinates_path, method: :get do %>
    <%= select_tag :owner_id, options_from_collection_for_select(Owner.man, :id, :name, params[:owner_id]), { include_blank: 'people' } %>
    <%= button_tag type: 'submit', class: 'btn btn-default' do %>
      <i class='fa fa-search'></i>
    <% end %>
  <% end %>
</div>

<% if current_user %>
  <% if current_user.email == 'takuyashiratake0622@icloud.com' || current_user.email == 'awesome_95@icloud.com' %>
    <div class='post text-center'>
      <%= link_to 'Post Corde', new_coordinate_path, class: 'btn btn-default' %>
    </div>
  <% end %>
<% end %>

<% if request.from_smartphone? %>
  <ul class='gallery_box'>
    <% @owners.each do |owner| %>
      <%= link_to man_path(id: owner.id) do %>
        <li class='gallery_list'>
          <div class='gallery_img_list'>
            <%= image_tag owner.coordinates.last.photos.last.image.url, class: 'gallery_img' %>
          </div>
        </li>
        <div class='gallery_bottom_info'>
          <span class='model_name'><%= owner.name %></span>
          <span class='occupation'><%= owner.occupation %></span>
        </div>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <ul class='pc_gallery_box'>
    <% @owners.each do |owner| %>
      <%= link_to man_path(id: owner.id) do %>
        <li class='gallery_list'>
          <div class='gallery_img_list'>
            <%= image_tag owner.coordinates.last.photos.last.image.url, class: 'gallery_img' %>
          </div>
          <div class='gallery_bottom_info'>
            <span class='model_name'><%= owner.name %></span>
            <span class='occupation'><%= owner.occupation %></span>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/men_coordinates/index.html.erb
<header class='search_form text-center'>
  <%= form_tag men_coordinates_path, method: :get do %>
    <%= select_tag :owner_id, options_from_collection_for_select(Owner.man, :id, :name, params[:owner_id]), { include_blank: 'people' } %>
    <%= button_tag type: 'submit', class: 'btn btn-default' do %>
      <i class='fa fa-search'></i>
    <% end %>
  <% end %>
</header>

<% if request.from_smartphone? %>
  <ul class='gallery_box'>
    <% @coordinates.each do |coordinate| %>
      <li class='gallery_list'>
        <div class='gallery_img_list'>
          <%= image_tag coordinate.photos.first.image.url, class: 'gallery_img' %>
        </div>
      </li>
      <div class='gallery_bottom_info'>
      </div>
    <% end %>
  </ul>
<% else %>
  <ul class='pc_gallery_box'>
    <% @coordinates.each do |coordinate| %>
      <li class='gallery_list'>
        <div class='gallery_img_list'>
          <%= image_tag coordinate.photos.first.image.url, class: 'gallery_img' %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/men_coordinates/show.html.erb
<div class='coordinate'>
  <div class='previous_next'>
    <% if @coordinate.previous(@coordinate.owner, @coordinate.id).present? %>
      <div class='previous text-center'>
        <%= link_to men_coordinate_path(id: @coordinate.previous(@coordinate.owner, @coordinate.id).id) do %>
          <i class="fa fa-angle-double-left fa-2x"></i>
        <% end %>
      </div>
    <% end %>

    <% if @coordinate.next(@coordinate.owner, @coordinate.id).present? %>
      <div class='next text-center'>
        <%= link_to men_coordinate_path(id: @coordinate.next(@coordinate.owner, @coordinate.id).id) do %>
          <i class="fa fa-angle-double-right fa-2x"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class='person_name text-center'>
    <%= @coordinate.owner.name %>
  </div>
  <div class='image'>
    <% @coordinate.photos.each do |photo| %>
      <%= image_tag photo.image.url, class: 'img-responsive' %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.voted_up_on? @coordinate %>
      <%= render 'coordinates/remove_from_favorites' %>
    <% else %>
      <%= render 'coordinates/add_to_favorites' %>
    <% end %>
  <% else %>
    <div class='not_login'>
      <%= render 'coordinates/add_to_favorites' %>
    </div>
  <% end %>
  <hr>
  <div class='dress_season text-center'>
    dress_season: <%= @coordinate.dress_season %>
  </div>
  <hr>
  <div class='occupation text-center'>
    occupation: <%= @coordinate.owner.occupation %>
  </div>
  <hr>

  <% if current_user %>
    <% if current_user.email == 'takuyashiratake0622@icloud.com' %>
      <div class='text-center'>
        <%= link_to 'Delete', coordinate_path, method: :delete, class: 'btn btn-default' %>
      </div>
    <% end %>
  <% end %>

  <div class='show_more text-center'>
    <%= link_to 'Show more', man_path(id: @coordinate.owner), class: 'btn btn-default' %>
  </div>
</div>

<script>
  jQuery(function() {
    $('.not_login').click(function() {
      location.href = '/users/sign_in';
    })
  });
</script>

app/views/mens/index.html.erb
<div class='search_form text-center'>
  <%= render 'coordinates/search' %>
</div>

<% if current_user %>
  <% if current_user.email == 'takuyashiratake0622@icloud.com' || current_user.email == 'awesome_95@icloud.com' %>
    <div class='post text-center'>
      <%= link_to 'Post Corde', new_coordinate_path, class: 'btn btn-default' %>
    </div>
  <% end %>
<% end %>

<div class='owner_list'>
  <% @owners.each do |owner| %>
    <%= link_to men_path(id: owner.id) do %>
      <div class='list'>
        <div class='list_body'>
          <% owner.coordinates.shuffle.first.photos.each do |photo| %>
            <%= image_tag photo.image.url, class: 'coordinate_image' %>
          <% end %>
          <div class='name'>
            <%= owner.name %>'s corde
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/mens_coordinates/show.html.erb
<div class='coordinate'>
  <div class='person_name text-center'>
    <%= @coordinate.owner.name %>
  </div>
  <div class='image'>
    <% @coordinate.photos.each do |photo| %>
      <%= image_tag photo.image.url, class: 'img-responsive' %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.voted_up_on? @coordinate %>
      <%= render 'coordinates/remove_from_favorites' %>
    <% else %>
      <%= render 'coordinates/add_to_favorites' %>
    <% end %>
  <% else %>
    <div class='not_login'>
      <%= render 'coordinates/add_to_favorites' %>
    </div>
  <% end %>
  <hr>
  <div class='dress_season text-center'>
    dress_season: <%= @coordinate.dress_season %>
  </div>
  <hr>
  <div class='occupation text-center'>
    occupation: <%= @coordinate.owner.occupation %>
  </div>
  <hr>

  <% if current_user %>
    <% if current_user.email == 'takuyashiratake0622@icloud.com' %>
      <div class='text-center'>
        <%= link_to 'Delete', coordinate_path, method: :delete, class: 'btn btn-default' %>
      </div>
    <% end %>
  <% end %>

  <div class='show_more text-center'>
    <%= link_to 'Show more', men_path(id: @coordinate.owner), class: 'btn btn-default' %>
  </div>
</div>

<script>
  jQuery(function() {
    $('.not_login').click(function() {
      location.href = '/users/sign_in';
    })
  });
</script>

app/views/users/shared/_links.html.erb
<div class='shared_links text-center'>
  <%- if controller_name != 'sessions' %>
    <%= link_to "Log in", new_session_path(resource_name), class: 'btn btn-default' %><br />
  <% end -%>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "Sign up", new_registration_path(resource_name), class: 'btn btn-default' %><br />
  <% end -%>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "Forgot your password?", new_password_path(resource_name), class: 'btn btn-default' %><br />
  <% end -%>

  <%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name), class: 'btn btn-default' %><br />
  <% end -%>

  <%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
    <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name), class: 'btn btn-default' %><br />
  <% end -%>

  <%- if devise_mapping.omniauthable? %>
    <%- resource_class.omniauth_providers.each do |provider| %>
      <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), class: 'btn btn-default' %><br />
    <% end -%>
  <% end -%>
</div>

app/views/women/index.html.erb
<div class='search_form text-center'>
  <%= form_tag women_coordinates_path, method: :get do %>
    <%= select_tag :owner_id, options_from_collection_for_select(Owner.woman, :id, :name, params[:owner_id]), { include_blank: 'people' } %>
    <%= button_tag type: 'submit', class: 'btn btn-default' do %>
      <i class='fa fa-search'></i>
    <% end %>
  <% end %>
</div>

<% if current_user %>
  <% if current_user.email == 'takuyashiratake0622@icloud.com' || current_user.email == 'awesome_95@icloud.com' %>
    <div class='post text-center'>
      <%= link_to 'Post Corde', new_coordinate_path, class: 'btn btn-default' %>
    </div>
  <% end %>
<% end %>

<% if request.from_smartphone? %>
  <ul class='gallery_box'>
    <% @owners.each do |owner| %>
      <%= link_to woman_path(id: owner.id) do %>
        <li class='gallery_list'>
          <div class='gallery_img_list'>
            <%= image_tag owner.coordinates.last.photos.last.image.url, class: 'gallery_img' %>
          </div>
        </li>
        <div class='gallery_bottom_info'>
          <span class='model_name'><%= owner.name %></span>
          <span class='occupation'><%= owner.occupation %></span>
        </div>
      <% end %>
    <% end %>
  </ul>
<% else %>
  <ul class='pc_gallery_box'>
    <% @owners.each do |owner| %>
      <%= link_to woman_path(id: owner.id) do %>
        <li class='gallery_list'>
          <div class='gallery_img_list'>
            <%= image_tag owner.coordinates.last.photos.last.image.url, class: 'gallery_img' %>
          </div>
          <div class='gallery_bottom_info'>
            <span class='model_name'><%= owner.name %></span>
            <span class='occupation'><%= owner.occupation %></span>
          </div>
        </li>
      <% end %>
    <% end %>
  </ul>
<% end %>

app/views/women_coordinates/index.html.erb
<header class='search_form text-center'>
  <%= form_tag women_coordinates_path, method: :get do %>
    <%= select_tag :owner_id, options_from_collection_for_select(Owner.woman, :id, :name, params[:owner_id]), { include_blank: 'people' } %>
    <%= button_tag type: 'submit', class: 'btn btn-default' do %>
      <i class='fa fa-search'></i>
    <% end %>
  <% end %>
</header>

<% if request.from_smartphone? %>
  <ul class='gallery_box'>
    <% @coordinates.each do |coordinate| %>
      <li class='gallery_list'>
        <div class='gallery_img_list'>
          <%= image_tag coordinate.photos.first.image.url, class: 'gallery_img' %>
        </div>
      </li>
      <div class='gallery_bottom_info'>
      </div>
    <% end %>
  </ul>
<% else %>
  <ul class='pc_gallery_box'>
    <% @coordinates.each do |coordinate| %>
      <li class='gallery_list'>
        <div class='gallery_img_list'>
          <%= image_tag coordinate.photos.first.image.url, class: 'gallery_img' %>
        </div>
      </li>
      <div class='gallery_bottom_info'>
      </div>
    <% end %>
  </ul>
<% end %>

app/views/women_coordinates/show.html.erb
<div class='coordinate'>
  <div class='previous_next'>
    <% if @coordinate.previous(@coordinate.owner, @coordinate.id).present? %>
      <div class='previous text-center'>
        <%= link_to women_coordinate_path(id: @coordinate.previous(@coordinate.owner, @coordinate.id).id) do %>
          <i class="fa fa-angle-double-left fa-2x"></i>
        <% end %>
      </div>
    <% end %>

    <% if @coordinate.next(@coordinate.owner, @coordinate.id).present? %>
      <div class='next text-center'>
        <%= link_to women_coordinate_path(id: @coordinate.next(@coordinate.owner, @coordinate.id).id) do %>
          <i class="fa fa-angle-double-right fa-2x"></i>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class='person_name text-center'>
    <%= @coordinate.owner.name %>
  </div>
  <div class='image'>
    <% @coordinate.photos.each do |photo| %>
      <%= image_tag photo.image.url, class: 'img-responsive' %>
    <% end %>
  </div>

  <% if current_user %>
    <% if current_user.voted_up_on? @coordinate %>
      <%= render 'coordinates/remove_from_favorites' %>
    <% else %>
      <%= render 'coordinates/add_to_favorites' %>
    <% end %>
  <% else %>
    <div class='not_login'>
      <%= render 'coordinates/add_to_favorites' %>
    </div>
  <% end %>
  <hr>
  <div class='dress_season text-center'>
    dress_season: <%= @coordinate.dress_season %>
  </div>
  <hr>
  <div class='occupation text-center'>
    occupation: <%= @coordinate.owner.occupation %>
  </div>
  <hr>

  <% if current_user %>
    <% if current_user.email == 'takuyashiratake0622@icloud.com' %>
      <div class='text-center'>
        <%= link_to 'Delete', coordinate_path, method: :delete, class: 'btn btn-default' %>
      </div>
    <% end %>
  <% end %>

  <div class='show_more text-center'>
    <%= link_to 'Show more', woman_path(id: @coordinate.owner), class: 'btn btn-default' %>
  </div>
</div>

<script>
  jQuery(function() {
    $('.not_login').click(function() {
      location.href = '/users/sign_in';
    })
  });
</script>